apiVersion: apps/v1
kind: Deployment
metadata:
  name:  lgo
  namespace: lgo
  labels:
    app:  lgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  lgo
    spec:
      containers:
      - image: yunabe/lgo
        name:  app
        resources:
          limits:
            cpu: "1000m"
            memory: "500M"
          requests:
            cpu: "500m"
            memory: "200M"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort:  8888
