apiVersion: v1
kind: PersistentVolume
metadata:
  name: lgo-pv
  namespace: db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/lgo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgo-pv-claim
  namespace: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  lgo
  namespace: lgo
  labels:
    app:  lgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  lgo
    spec:
      containers:
      - image: yunabe/lgo
        name:  app
        resources:
          limits:
            cpu: "1000m"
            memory: "500M"
          requests:
            cpu: "500m"
            memory: "200M"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort:  8888
        volumeMounts:
            - name: lgo-pv-claim-lgo
              mountPath: /lgo
              subPath: lgo
            - name: lgo-pv-claim-examples
              mountPath: /examples
              subPath: examples
      volumes:
        - name: lgo-pv-claim
          persistentVolumeClaim:
            claimName: lgo-pv-claim
