kind: Service
apiVersion: v1
metadata:
  name: lgo
  namespace: lgo
spec:
  selector:
    app:  lgo
  type:  NodePort
  ports:
  - nodePort: 8888
    port: 8888
    protocol: TCP
    targetPort: 8888
